export const Statuses = [
    {id: 0,labelEn: 'NewReserve' , labelFa : 'درخواست جدید' },
    {id: 0,labelEn: 'Completion' , labelFa : 'در حال تکمیل' },
    {id: 0,labelEn: 'Accepted' , labelFa : 'تایید شده' },
    {id: 0,labelEn: 'NotAccepted' , labelFa : 'تایید نشده' },
    {id: 0,labelEn: 'Pending' , labelFa : 'در انتظار' },
    {id: 0,labelEn: 'Suspended' , labelFa : 'معلق شده' },
    {id: 0,labelEn: 'Show' , labelFa : 'نمایش' },
    {id: 0,labelEn: 'Draft' , labelFa : 'پیش نویس' },
    {id: 0,labelEn: 'NewTicket' , labelFa : 'تیکت جدید' },
    {id: 0,labelEn: 'ExpertAnswerTicket' , labelFa : 'پاسخ کارشناس به تیکت' },
    {id: 0,labelEn: 'UserAnswerTicket' , labelFa : 'پاسخ تیکت کاربر' },
    {id: 0,labelEn: 'ExpertCheckingTicket' , labelFa : 'بررسی تیکت کارشناس' },
    {id: 0,labelEn: 'closeTicket' , labelFa : 'بستن تیکت' },
    {id: 0,labelEn: 'NewReserve' , labelFa : 'رزرو جدید' },
    {id: 0,labelEn: 'PenddingAccept' , labelFa : 'منتظر تایید آژانس' },
    {id: 0,labelEn: 'Paid' , labelFa : 'پرداخت شده' },
    {id: 0,labelEn: 'PenddingPay' , labelFa : 'منتظر پرداخت' },
    {id: 0,labelEn: 'Completed' , labelFa : 'تکمیل شده' },
]
export const TourStatuses = [
    {id: 0,labelEn: 'NewReserve' , labelFa : 'درخواست جدید' },
    {id: 0,labelEn: 'Completion' , labelFa : 'در حال تکمیل' },
    {id: 0,labelEn: 'Accepted' , labelFa : 'تایید شده' },
    {id: 0,labelEn: 'NotAccepted' , labelFa : 'تایید نشده' },
    {id: 0,labelEn: 'Pending' , labelFa : 'در انتظار' },
    {id: 0,labelEn: 'Suspended' , labelFa : 'معلق شده' },
    {id: 0,labelEn: 'Show' , labelFa : 'نمایش' },
    {id: 0,labelEn: 'Draft' , labelFa : 'پیش نویس' },
    {id: 0,labelEn: 'NewTicket' , labelFa : 'تیکت جدید' },
    {id: 0,labelEn: 'NewReserve' , labelFa : 'رزرو جدید' },
    {id: 0,labelEn: 'PenddingAccept' , labelFa : 'منتظر تایید آژانس' },
    {id: 0,labelEn: 'Paid' , labelFa : 'پرداخت شده' },
    {id: 0,labelEn: 'PenddingPay' , labelFa : 'منتظر پرداخت' },
    {id: 0,labelEn: 'Completed' , labelFa : 'تکمیل شده' },
]